//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaRabota
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class CityLibraryEntities : DbContext
    {
        public CityLibraryEntities()
            : base("name=CityLibraryEntities")
        {
        }

        private static CityLibraryEntities _context;

        public static CityLibraryEntities GetContext()
        {
            if (_context == null)
            {
                _context = new CityLibraryEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<withTriggers> withTriggers { get; set; }
        public virtual DbSet<Библиотеки> Библиотеки { get; set; }
        public virtual DbSet<Выдача_литературы> Выдача_литературы { get; set; }
        public virtual DbSet<Литература> Литература { get; set; }
        public virtual DbSet<Читальные_залы> Читальные_залы { get; set; }
        public virtual DbSet<Читатели> Читатели { get; set; }
    }
}
