//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaRabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выдача_литературы
    {
        public int ID_выдачи { get; set; }
        public int Читатель_ID { get; set; }
        public int Литература_ID { get; set; }
        public System.DateTime Дата_выдачи { get; set; }
        public string Срок_выдачи { get; set; }
        public string Вид_выдачи { get; set; }
        public string Наличие_залога { get; set; }
        public Nullable<decimal> Сумма_залога { get; set; }
        public Nullable<System.DateTime> Дата_сдачи { get; set; }
        public string Книга_сдана_не_сдана { get; set; }
    
        public virtual Литература Литература { get; set; }
        public virtual Читатели Читатели { get; set; }
    }
}
