//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaRabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Литература
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Литература()
        {
            this.Выдача_литературы = new HashSet<Выдача_литературы>();
        }
    
        public int ID_литературы { get; set; }
        public string Название { get; set; }
        public string Категория_литературы { get; set; }
        public string Авторы { get; set; }
        public string Издательство { get; set; }
        public int Год_издательства { get; set; }
        public int Кол_во_страниц { get; set; }
        public int Читальный_зал_ID { get; set; }
        public int Кол_во_единиц_лит_ры { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выдача_литературы> Выдача_литературы { get; set; }
        public virtual Читальные_залы Читальные_залы { get; set; }
    }
}
