//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaRabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Читальные_залы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Читальные_залы()
        {
            this.Литература = new HashSet<Литература>();
        }
    
        public int ID_зала { get; set; }
        public string Название_зала { get; set; }
        public int Библиотека_ID { get; set; }
        public int Кол_во_посадочных_мест { get; set; }
        public string Время_работы { get; set; }
        public int Этаж { get; set; }
        public int Кол_во_сотрудников { get; set; }

        
    
        public virtual Библиотеки Библиотеки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Литература> Литература { get; set; }
    }
}
