//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaRabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Читатели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Читатели()
        {
            this.Выдача_литературы = new HashSet<Выдача_литературы>();
        }
    
        public int ID_читателя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Категория_читателя { get; set; }
        public string Место_работы_или_обучения { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
        public int Библиотека_ID { get; set; }
    
        public virtual Библиотеки Библиотеки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выдача_литературы> Выдача_литературы { get; set; }
    }
}
